name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 */2 * *'  # Run at midnight UTC every 2 days
  workflow_dispatch:  # Allow manual triggering via GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Build site
      run: npm run generate 
      env:
        AIRTABLEKEY: ${{ secrets.AIRTABLEKEY }}
        BUTTERKEY: ${{ secrets.BUTTERKEY }}
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./.output/public
  deploy:
    needs: build

    permissions:
      pages: write      
      id-token: write 

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4